# Generated by Django 3.1.5 on 2021-04-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bind_hosts',
            field=models.ManyToManyField(blank=True, to='audit.BindHost'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_group',
            field=models.ManyToManyField(blank=True, to='audit.HostGroup'),
        ),
    ]
